version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - .:/code
  db:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: sample01_db
